In [14]:
my_list=[1,2,3,4,5,6]

In [15]:
print(my_list)

[1, 2, 3, 4, 5, 6]


In [16]:
import numpy as np

In [26]:
arr=np.array(my_list,dtype=int )

In [27]:
print(arr)

[1 2 3 4 5 6]


In [28]:
print(type(arr))
print(len(arr))
print(arr.ndim)
print(arr.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [29]:
    arr2=arr.reshape(3,2)
print(arr2)
arr2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [30]:
 arr3=arr.reshape(3,-1)
print(arr3)
arr3.ndim

[[1 2]
 [3 4]
 [5 6]]


2

In [31]:
arr3.shape

(3, 2)

In [32]:
my_list2=[1,2,3,4]
my_list3=[5,6,7,8]
my_list4=[9,10,11,12]

In [35]:
mul_array=np.array([my_list2,my_list3,my_list4])
print(mul_array)
print(mul_array.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [38]:
mul_array.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [43]:
mul_array.shape=(2,6)

In [44]:
print(mul_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [45]:
r=range(24)

In [46]:
print(r)

range(0, 24)


In [50]:
for x in r : print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [52]:
a=np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [53]:
b=a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [58]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x)
print(x.shape)
print(x.ndim)
print(y)
print(y.shape)
print(y.ndim)
z=x+y
print(z)
u=x-z
print(u)


[[1. 2.]
 [3. 4.]]
(2, 2)
2
[[5. 6.]
 [7. 8.]]
(2, 2)
2
[[ 6.  8.]
 [10. 12.]]
[[-5. -6.]
 [-7. -8.]]


In [59]:
v=x*y  #element-wise multiplication
print(v)


[[ 5. 12.]
 [21. 32.]]


In [57]:
w=x.dot(y)   #matrix multiplication 
print(W)

[[19. 22.]
 [43. 50.]]


In [61]:
t=np.dot(x,y)
print(t)

[[19. 22.]
 [43. 50.]]


In [62]:
s=x/y
print(s)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [64]:
r=np.divide(x,y) #another way to divide
print(r)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [68]:
print(np.sum(x))
print(x)

10.0
[[1. 2.]
 [3. 4.]]


In [71]:
print(np.sum(x,axis=0)) #print sum of all rows

[4. 6.]


In [72]:
print(np.sum(x,axis=1)) #print sum of all cloumns

[3. 7.]
