1) Numpy is linear aplgebra library in python
2) The reason why is so important for data science with pythonis that almost all libraries in python depend on Numpy as on of the main building blocks
3) Numpy is incredibly fast, as it has bindings to C libraries
4) Install numpy by using command prompt, by typing conda install numpy or pip install numpy
5) Numpy arrays are objects on which we perform operation using numpy
6) Numpy arrays essentially comes in two flavors:vectors and matrices
7) vectors are 1-d arrays and matrices are2-d 


In [82]:
my_list=[1,2,3,4]

In [83]:
my_list


[1, 2, 3, 4]

In [2]:
import numpy as np

In [85]:
arr=np.array(my_list) #To convert list into numpy array

In [86]:
arr

array([1, 2, 3, 4])

In [87]:
arr.shape #give dimension of array

(4,)

In [88]:
arr.shape

(4,)

In [89]:
my_mat=[[1,2,3,4],[2,3,4,5],[2,3,4,5]] #to convert list of lists as numpy array(will give multidimensional array)

In [90]:
mat=np.array(my_mat)


In [91]:
print(mat)

[[1 2 3 4]
 [2 3 4 5]
 [2 3 4 5]]


In [92]:
mat.ndim #give dimension

2

In [93]:
ra=np.arange(0,10) #create numpy array using range, will exculde the last value

In [94]:
print(ra)

[0 1 2 3 4 5 6 7 8 9]


In [95]:
ra1=np.arange(0,10,2) #create range in interval of 2, will exclude the last value

In [96]:
print(ra1)

[0 2 4 6 8]


In [97]:
np.zeros(3) #will give one dimensional array of 3 zeros

array([0., 0., 0.])

In [98]:
np.zeros((5,5)) #can pass a tuple of two values inside to get two dimensional arrays, 
#first number in tuple represent number of rows and second represent number of columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [99]:
np.zeros((2,5))
         

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
np.ones(3)

array([1., 1., 1.])

In [101]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [102]:
np.linspace(0,5,10) #will produce 10 evenly spaced points from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [103]:
np.linspace(0,5,100) #will produce 1-d array of 100 evenly spaced points from 0 to 5

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [104]:
np.eye(4) #will produce identity matrix of 4 X 4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [105]:
np.random.rand() #will give random sample from uniform distribution over 0 to 1

0.6505945647627934

In [106]:
np.random.rand(5) #will give 5 X 5 matrix of random values from unform distributed from  0 to 1
#will give random numbers from uniform distribution

array([0.03287697, 0.23059188, 0.77186825, 0.53012119, 0.96183429])

In [107]:
  np.random.rand(5,5)  #will give 5 X 5 matrix of random values from unform distributed from  0 to 1
    #will give random numbers from uniform distribution

array([[0.54734437, 0.59150556, 0.40400635, 0.96269482, 0.17813345],
       [0.52569946, 0.87615957, 0.06255625, 0.394391  , 0.34796626],
       [0.83676822, 0.20079568, 0.58514494, 0.76691113, 0.16327599],
       [0.38278249, 0.89511845, 0.89954111, 0.22889524, 0.17345096],
       [0.68845207, 0.74283751, 0.77698311, 0.58650179, 0.36677223]])

In [108]:
np.random.randn() #will give random numbers from normal distribution

-0.0190404921543175

In [109]:
np.random.randn(5)

array([-0.92174922, -1.80231403, -0.82009138, -0.98413471, -0.26653031])

In [110]:
np.random.randn(5,5) 

array([[-0.2003325 ,  0.20484986,  0.87695047,  1.50305601, -0.89404969],
       [-0.96910675, -0.22995345,  0.48555709, -0.36295746,  0.83191334],
       [-0.50179394,  0.42335864,  0.56828297, -0.62405597, -0.02983723],
       [-0.04753269, -1.78811443, -0.64432677,  0.31638085, -0.76086438],
       [ 0.76644334, -0.8893893 ,  0.61297801, -0.44341774, -0.63311889]])

In [111]:
np.random.randint(1,100) #will give any random integer from 1 to 100

33

In [112]:
np.random.randint(1,100,10) #will give array of any 10 random integer from 1 to 100

array([83, 42, 25, 65, 31, 85, 48, 70, 18, 84])

In [113]:
arr=np.random.randint(1,100,25)

In [114]:
arr.reshape(5,5)

array([[73,  9, 16, 39, 49],
       [87, 37, 65, 36, 94],
       [19, 83, 35, 87, 62],
       [23, 22, 50, 86, 78],
       [95, 31, 16, 93, 36]])

In [115]:
arr.shape

(25,)

In [116]:
arr.max() #will return the maximum value

95

In [117]:
arr.min() #will return the minimum value

9

In [118]:
arr.argmax() #will return index of maximum value

20

In [119]:
arr.argmin() #will return index of minimum value

1

In [122]:
a=arr.reshape(5,5) #will reshape arr and store in variable a

In [123]:
a.shape #will give dimension of array

(5, 5)

In [125]:
from numpy.random import randint #will import randint from numpy.random

In [131]:
randint(2,10)

9

# Indexing from numpy array

In [22]:
r=np.arange(0,36)

In [24]:
r.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [25]:
r[0:6,::-7]

IndexError: too many indices for array

In [27]:
r[:,::7]

IndexError: too many indices for array

In [32]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [8]:
arr=np.arange(0,11)

In [9]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[7] #will give value at index 7

7

In [12]:
arr[1:7] #will give all elements starting from index1 and stop at index6(using slicing operator)


array([1, 2, 3, 4, 5, 6])

In [135]:
arr[0:5] #will start at index 0 and will give 5 elements 

array([0, 1, 2, 3, 4])

In [136]:
arr[:5] #will give from starting of array till index 4 i.e 5 elements from starting

array([0, 1, 2, 3, 4])

In [137]:
arr[5:] #will give elements starting from index 5 till end of array

array([ 5,  6,  7,  8,  9, 10])

In [139]:
slice_of_arr=arr[:6]

In [140]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [141]:
slice_of_arr[:]=99 #broad casting all values to 99

In [142]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [143]:
arr #changes in slice_of_arr is also reflected in arr, this is done to avoid memory issues, to avoid this we use copy method

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [144]:
arr_copy=arr.copy()

In [146]:
arr_copy[:]=100 #broadcasting all values to 100

In [147]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [148]:
arr_copy


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [4]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]]) #will give 2-d array of dimension 3 X 3

In [5]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr_2d.reshape(9)[::4]

array([1, 5, 9])

In [16]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr_2d[:,:]

array([[1],
       [4],
       [7]])

In [7]:
arr_2d[0][0]

1

In [161]:
arr_2d[0,0]

1

In [162]:
arr_2d[2][2]

9

In [163]:
arr_2d[2,2]

9

In [156]:
arr_2d[2][1]

8

In [158]:
arr_2d[0] #will give entire row with index 0

array([1, 2, 3])

In [164]:
arr_2d[:2,1:] #will inculde all data in (0 and 1) row and (1 and 2) column 

array([[2, 3],
       [5, 6]])

In [165]:
arr_2d[:2] #will give first and zero row

array([[1, 2, 3],
       [4, 5, 6]])

In [167]:
arr=np.arange(1,11)

In [168]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
arr>5 #will give boolean values of wheter all elements are more than 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [170]:
bool_array=arr>5

In [171]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [172]:
arr[arr>5] #will give only those elements of arr which are more than 5

array([ 6,  7,  8,  9, 10])

In [173]:
arr[arr<3] #will give all elements which are less than 3

array([1, 2])

In [3]:
arr_2d=np.arange(50).reshape(5,10)

In [5]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [12]:
arr_2d[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy operations

In [178]:
arr=np.arange(0,11)

In [179]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [180]:
arr+arr #will give element to element addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [181]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [182]:
arr*arr


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [183]:
arr/arr #will give warning since anything divided by 0 is not defined

C:\Users\krish\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [184]:
arr+100 #will add 100 with all elements of arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [185]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [186]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [187]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [188]:
arr**2 #give square of all elements

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [189]:
np.sqrt(arr) #will give square root of all elements of array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [191]:
a=np.exp(arr)

In [192]:
a


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [196]:
a[6]


403.4287934927351

In [197]:
np.max(arr)

10

In [198]:
arr.max()

10

In [199]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [200]:
np.log(arr) #gives warning since log(0) is negative infinity

C:\Users\krish\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])